// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdvtP7utQxpryV6UurQmVbFcKE2-nah7o',
    appId: '1:162395769112:web:08cd883d0302877d95366d',
    messagingSenderId: '162395769112',
    projectId: 'egyptous-59584',
    authDomain: 'egyptous-59584.firebaseapp.com',
    storageBucket: 'egyptous-59584.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN0OMGAHJChJsfnHSLHwCzZ-GDhUnrscE',
    appId: '1:162395769112:android:74513e1de850ff3795366d',
    messagingSenderId: '162395769112',
    projectId: 'egyptous-59584',
    storageBucket: 'egyptous-59584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFbCsOw6CjAfYpKv6gEpJJvPZXOVM3Cpo',
    appId: '1:162395769112:ios:b7c51094503951ca95366d',
    messagingSenderId: '162395769112',
    projectId: 'egyptous-59584',
    storageBucket: 'egyptous-59584.firebasestorage.app',
    androidClientId: '162395769112-fvblpfi24fnjcm1phus5spq3ajr1l9op.apps.googleusercontent.com',
    iosClientId: '162395769112-mcd1snviv0sjrps1ap2aud0vfovndrja.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFbCsOw6CjAfYpKv6gEpJJvPZXOVM3Cpo',
    appId: '1:162395769112:ios:b7c51094503951ca95366d',
    messagingSenderId: '162395769112',
    projectId: 'egyptous-59584',
    storageBucket: 'egyptous-59584.firebasestorage.app',
    androidClientId: '162395769112-fvblpfi24fnjcm1phus5spq3ajr1l9op.apps.googleusercontent.com',
    iosClientId: '162395769112-mcd1snviv0sjrps1ap2aud0vfovndrja.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdvtP7utQxpryV6UurQmVbFcKE2-nah7o',
    appId: '1:162395769112:web:96426214235cbf3195366d',
    messagingSenderId: '162395769112',
    projectId: 'egyptous-59584',
    authDomain: 'egyptous-59584.firebaseapp.com',
    storageBucket: 'egyptous-59584.firebasestorage.app',
  );
}
